{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "guestbook-ui.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.rollout.strategy.blueGreen.activeService }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
