rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
          backend:
            service:
              name: {{ .Values.rollout.strategy.blueGreen.activeService }}
              port:
                number: {{ .Values.service.port }}