apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.activeService }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "guestbook-ui.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.previewService }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "guestbook-ui.name" . }}
