apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/udemykcloud/helm.git'
    path: helm-charts/guestbook-ui
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
