replicaCount: 5

image:
  repository: udemykcloud534/guestbook
  tag: prod
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Rollout settings (avoid nil pointer in templates)
rollout:
  strategy:
    blueGreen:
      activeService: guestbook-ui-prod
      previewService: guestbook-ui-prod-preview
      autoPromotionEnabled: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: guestbook.systemsdesigns.xyz
      paths:
        - path: /
          pathType: Prefix   # ✅ required by Kubernetes
  tls: []
