replicaCount: 5

image:
  repository: udemykcloud534/guestbook
  tag: prod
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: guestbook.systemsdesigns.xyz
      paths:
        - path: /
          pathType: Prefix
  tls: []
